# Site settings
title: SNT Toolbox Manual
description: A step-by-step guide for SNT Analytics in OpenHexa.

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# This tells the theme to use the side-nav
nav_sort: nav_order

# Color scheme
color_scheme: light

# Search settings
search_enabled: true
search:
  rel_url: true
