# Site settings
title: SNT Toolbox Manual
description: A step-by-step guide for SNT Analytics in OpenHexa.

# Theme settings
# We use the remote_theme plugin to load Just the Docs
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme (can be 'light' or 'dark')
color_scheme: light
